Suggest renaming stub() / stubbed() to register() / invoke()
devxoul/Stubber pull request #1
Opened 2017-08-17 13:14 UTC by innocarpe

I suggest this PR because it's a little hard to understand the mechanism of `Stubber` because of these method signatures. 

I think `register()` / `invoke()` is giving easier understanding to user programmers than previous pair `stub()` / `stubbed()`, so please consider this suggestion :)

2017-08-17 14:40 UTC, devxoul commented
I like it. However it is a breaking API change, so how about marking old methods as deprecated?

2017-08-18 03:10 UTC, innocarpe commented
@devxoul You're right. How about this?

- Before & After
<img width="2690" alt="output" src="https://user-images.githubusercontent.com/2222333/29442688-2971b9ee-840e-11e7-8586-5cf944788c6b.png">

2017-08-18 04:48 UTC, devxoul commented on Sources/Stubber.swift
> +@available(*, deprecated: 1.0, message: "Please use invoke(_: args:")
You can instead:

```swift
@available(*, deprecated, renamed: "invoke(_:args:)")
```

2017-08-18 04:50 UTC, devxoul requested changes

2017-08-18 04:50 UTC, devxoul commented on Sources/Stubber.swift
> +@available(*, deprecated: 1.0, message: "Please use register(_: with:))")
You can use `deprecated:` without a specific version and use `renamed:`:

```swift
@available(*, deprecated, renamed: "register(_:with:)")
```

2017-08-18 04:50 UTC, devxoul commented on Sources/Stubber.swift
> +@available(*, deprecated: 1.0, message: "Please use invoke(_: args:")
You can use `deprecated:` without a specific version and use `renamed:`:

```swift
@available(*, deprecated, renamed: "invoke(_:args:)")
```

2017-08-18 05:08 UTC, innocarpe commented on Sources/Stubber.swift
> +@available(*, deprecated: 1.0, message: "Please use register(_: with:))")
Thanks for your review. I'm going to push new changes right after :)

2017-08-18 05:08 UTC, innocarpe commented on Sources/Stubber.swift
> +@available(*, deprecated: 1.0, message: "Please use invoke(_: args:")
Thanks for your review. I'm going to push new changes right after :)

2017-08-18 05:18 UTC, innocarpe commented
I pushed the changes you reviewed!

2017-08-18 05:30 UTC, devxoul approved these changes

2017-08-18 09:04 UTC, merged